name: Replace current folder with latest release

on:
  workflow_dispatch:
  #schedule:
  #- cron: "30 06 11 * *"

jobs:
  replace-current:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Replace current
        run: echo "TODO"