name: 3. Replace current folder with latest release

on:
  workflow_dispatch:
  #schedule:
  #- cron: "30 06 11 * *"

jobs:
  replace-current:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Replace current
        run: |
          latest=0
          for d in ./*; do
            echo $d
            if [[ -d "$d" && ${#d} -eq 10 ]]; then
              num=${d: -8}
              if [[ $num -gt $latest ]]; then
                latest=$num
              fi
            fi
          done
          rm -rf current
          mkdir current
          cp -R $latest/* current/.